### ISSUE TITLE
Aufsetzen neues Webprojekt (2PT)

### ISSUE THREAD

**Issue by jmuheim** [Access4all/a4aa2-old#1]

**Comment by AndreasUe** [comment]
Sehr geehrte Mailsenderin,
sehr geehrter Mailsender,

Danke für Ihre Nachricht.
Ferienbedingt bin ich erst am 24.Februar 2015 wieder im Büro verfügbar.
Ihre Nachricht wird nicht weitergeleitet, mit einer verzögerten Bearbeitung ist deshalb zu rechnen.

In dringenden Fällen möchte ich Sie bitten, sich während dieser Zeit an Joshua Muheim (joshua.muheim@access-for-all.ch) zu wenden.

Ich danke Ihnen für Ihr Verständnis.

Mit freundlichen Grüssen,
Andreas Uebelbacher

****************
Dear mailsender,

Thank you for your message.
I am not in the office until Monday, February 24th.
Your message will not be forwarded, a delayed response must therefore be expected.

In urgent cases, please get in touch with Joshua Muheim (joshua.muheim@access-for-all.ch).

Thank you for your understanding.

Best wishes,
Andreas Uebelbacher

Leiter Dienstleistungen

«Zugang für alle»
Schweizerische Stiftung zur
behindertengerechten Technologienutzung
Dörflistrasse 10
CH-8057 Zürich

Tel. 	       +41 (0)44 515 5422
E-Mail	andreas.uebelbacher@access-for-all.ch 
Web 	        www.access-for-all.ch/ 
Blog  	www.access4all.ch/blog/ 
Twitter	http://twitter.com/access4all

**Comment by jmuheim** [comment]
This issue was moved to Access4all/a4aa2#1
